name: Eleventy Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Build
        uses: TartanLlama/actions-eleventy@master
      - name: Upload
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: _site
  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages
